lin3s_admin_list:
    path: /{entity}/list
    defaults: { _controller: LIN3SAdminBundle:Admin:list }
    methods:  [GET]

lin3s_admin_new:
    path: /{entity}/new
    defaults: { _controller: LIN3SAdminBundle:Admin:new }
    methods:  [GET,POST]

lin3s_admin_edit:
    path: /{entity}/edit/{id}
    defaults: { _controller: LIN3SAdminBundle:Admin:edit }
    methods:  [GET,POST]

lin3s_admin_batch:
    path: /{entity}/batch/{id}/{action}
    defaults: { _controller: LIN3SAdminBundle:Admin:batch }
    methods:  [GET]

lin3s_admin_dashboard:
    path: /
    defaults: { _controller: LIN3SAdminBundle:Dashboard:index }
