# This file is part of the Admin Bundle.
#
# Copyright (c) 2015-2016 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

services:
    lin3s_admin.action.type.new:
        class: LIN3S\AdminBundle\Extension\Action\NewActionType
        arguments:
            - '@lin3s_admin.form.handler'
            - '@twig'
            - '@session'
            - '@router'
        tags:
            - { name: 'lin3s_admin.action', alias: new }

    lin3s_admin.action.type.edit:
        class: LIN3S\AdminBundle\Extension\Action\EditActionType
        arguments:
            - '@lin3s_admin.form.handler'
            - '@doctrine.orm.default_entity_manager'
            - '@twig'
            - '@session'
        tags:
            - { name: 'lin3s_admin.action', alias: edit }

    lin3s_admin.action.type.delete:
        class: LIN3S\AdminBundle\Extension\Action\DeleteActionType
        arguments:
            - '@router'
            - '@doctrine.orm.default_entity_manager'
            - '@twig'
            - '@session'
        tags:
            - { name: 'lin3s_admin.action', alias: delete }

    lin3s_admin.action.type.handle_command:
        class: LIN3S\AdminBundle\Extension\Action\HandleCommandActionType
        arguments:
            - "@lin3s_admin.form.handler"
            - "@lin3s.cms_kernel.application.command_bus"
            - "@twig"
            - "@session.flash_bag"
            - "@router"
        tags:
            - { name: "lin3s_admin.action", alias: handle_command }
