lin3s_admin_list:
    path: /{entity}
    defaults:
        _controller: LIN3SAdminBundle:Admin:list
    methods:  [GET]

lin3s_admin_custom:
    path: /{entity}/{action}/{id}
    defaults:
        _controller: LIN3SAdminBundle:Admin:custom
        id: null
    methods:  [GET,POST]

lin3s_admin_dashboard:
    path: /
    defaults: { _controller: LIN3SAdminBundle:Dashboard:index }
