# This file is part of the Admin Bundle.
#
# Copyright (c) 2015-2016 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

lin3s_admin_list:
    path: /{entity}/
    defaults:
        _controller: LIN3SAdminBundle:Admin:list
    methods:
        - GET

lin3s_admin_custom:
    path: /{entity}/{action}/{id}/
    defaults:
        _controller: LIN3SAdminBundle:Admin:custom
        id: null
    methods:
        - GET
        - POST

lin3s_admin_dashboard:
    path: /
    defaults: { _controller: LIN3SAdminBundle:Dashboard:index }
