# This file is part of the Admin Bundle.
#
# Copyright (c) 2015-2016 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

services:
    ## ACTIONS ##
    lin3s_admin.action.registry:
        class: LIN3S\AdminBundle\Action\Registry\ActionRegistry

    lin3s_admin.action.type.new:
        class: LIN3S\AdminBundle\Action\Type\NewActionType
        arguments: ['@lin3s_admin.form.handler', '@twig', '@session', '@router']
        tags:
            - { name: 'lin3s_admin.action' }

    lin3s_admin.action.type.edit:
        class: LIN3S\AdminBundle\Action\Type\EditActionType
        arguments: ['@lin3s_admin.form.handler', '@doctrine.orm.default_entity_manager', '@twig', '@session']
        tags:
            - { name: 'lin3s_admin.action' }

    lin3s_admin.action.type.delete:
        class: LIN3S\AdminBundle\Action\Type\DeleteActionType
        arguments: ['@router', '@doctrine.orm.default_entity_manager', '@twig', '@session']
        tags:
            - { name: 'lin3s_admin.action' }

    ## CONFIGURATION ##
    lin3s_admin.configuration.entity_configuration_registry:
        class: LIN3S\AdminBundle\Configuration\Registry\EntityConfigurationRegistry


    ## EVENT LISTENERS ##
    lin3s_admin.event_listener.entity_configuration_annotation:
        class: LIN3S\AdminBundle\EventListener\EntityConfigurationAnnotationListener
        arguments: ['@annotation_reader', '@lin3s_admin.configuration.entity_configuration_registry']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }


    ## FORM ##
    lin3s_admin.form.handler:
        class: LIN3S\AdminBundle\Form\FormHandler
        arguments: ['@form.factory', '@doctrine.orm.default_entity_manager']


    ## LIST FIELDS ##
    lin3s_admin.list_field_type.registry:
        class: LIN3S\AdminBundle\ListFields\ListFieldTypeRegistry

    lin3s_admin.list_field_type.string:
        class: LIN3S\AdminBundle\ListFields\Types\StringListFieldType
        tags:
            - {name: lin3s_admin.list_field_type}


    ## LIST FILTERS ##
    lin3s_admin.list_filter_type.registry:
        class: LIN3S\AdminBundle\ListFilters\ListFilterTypeRegistry

    lin3s_admin.list_filter_type.text:
        class: LIN3S\AdminBundle\ListFilters\Types\TextListFilterType
        tags:
            - {name: lin3s_admin.list_filter_type}
    lin3s_admin.list_field_type.date:
             class: LIN3S\AdminBundle\ListFields\Types\DateListFieldType
             tags:
                - {name: lin3s_admin.list_filter_date}


    ## REPOSITORY ##
    lin3s_admin.repository:
        class: LIN3S\AdminBundle\Repository\AdminRepository

    lin3s.admin.repository.default_query_builder:
        class: LIN3S\AdminBundle\Repository\DefaultQueryBuilder
        arguments: ['@doctrine.orm.default_entity_manager']


    ## TWIG ##
    lin3s_admin.twig.filter_path:
        class: LIN3S\AdminBundle\Twig\TwigFilterPathFunction
        arguments: ['@router', '@request_stack']
        tags:
            - { name: twig.extension }

    lin3s_admin.twig.paginator_path:
        class: LIN3S\AdminBundle\Twig\TwigPaginatorPathFunction
        arguments: ['@router', '@request_stack']
        tags:
            - { name: twig.extension }
