# This file is part of the Admin Bundle.
#
# Copyright (c) 2015-2016 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

imports:
    - { resource: services/actions.yml }
    - { resource: services/list_fields.yml }
    - { resource: services/list_filters.yml }
    - { resource: services/registry.yml }
    - { resource: services/twig.yml }

services:
    ## EVENT LISTENERS ##
    lin3s_admin.event_listener.entity_configuration_annotation:
        class: LIN3S\AdminBundle\EventListener\EntityConfigurationAnnotationListener
        arguments:
            - '@annotation_reader'
            - '@lin3s_admin.configuration.entity_configuration_registry'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    ## FORM ##
    lin3s_admin.form.handler:
        class: LIN3S\AdminBundle\Form\FormHandler
        arguments:
            - '@form.factory'
            - '@doctrine.orm.default_entity_manager'

    ## REPOSITORY ##
    lin3s_admin.repository:
        class: LIN3S\AdminBundle\Repository\AdminRepository
    lin3s.admin.repository.default_query_builder:
        class: LIN3S\AdminBundle\Repository\DefaultQueryBuilder
        arguments:
            - '@doctrine.orm.default_entity_manager'


